### ISSUE TITLE
pymatching timing data appears extremely inaccurate

### ISSUE THREAD

**Issue by Strilanc** [qc-design/plaquette-unionfind#3]
In your README you claim that pymatching takes 1 millisecond to decode a distance 40 surface code under code capacity noise.

When I test this for myself, I find that it actually takes 0.1 milliseconds per shot. This is a 10x difference.

A more minor point is that the README claims that using the batch decoding method is less representative of the actual speed of the decoder. This is wrong. Not using the batch decoding method is actually timing how long it takes python to repeatedly allocate and garbage collect temporary objects used to transfer data, with less of the actual time being spent in the decoder. In fact, ideally, you would call pymatching from the command line to completely remove the python overhead.

Here is the code I used to get this timing data:

```
import time

import numpy as np
import pymatching
import stim


def make_surface_code_capacity_circuit(d: int, p: float) -> stim.Circuit:
    qubit_set = {
        x + 1j*y
        for x in range(2*d - 1)
        for y in range(2*d - 1)
    }
    data_qubit_set = {q for q in qubit_set if (q.real + q.imag) % 2 == 0}
    measure_qubit_set = qubit_set - data_qubit_set
    sorted_measures = sorted(measure_qubit_set, key=lambda e: (e.real, e.imag))
    sorted_data = sorted(data_qubit_set, key=lambda e: (e.real, e.imag))
    q2i = {q: i for i, q in enumerate(sorted_data)}

    circuit = stim.Circuit()
    for q, i in q2i.items():
        circuit.append('QUBIT_COORDS', [i], [q.real, q.imag])

    obs_targets = []
    for d in sorted_data:
        if d.real == 0:
            obs_targets.append(stim.target_z(q2i[d]))
            obs_targets.append(stim.target_combiner())
    obs_targets.pop()

    # Prepare observable beforehand.
    circuit.append('MPP', obs_targets)

    # Measure stabilizers before/after noise.
    for layer in range(2):
        for m in sorted_measures:
            adjacent_data = {m + 1j**k for k in range(4)} & data_qubit_set
            basis = 'X' if m.real % 2 == 0 else 'Z'
            t = stim.target_x if basis == 'X' else stim.target_z
            targets = []
            for d in adjacent_data:
                targets.append(t(q2i[d]))
                targets.append(stim.target_combiner())
            targets.pop()
            circuit.append('MPP', targets)
        if layer == 0:
            circuit.append('DEPOLARIZE1', range(len(q2i)), p)
    # Declare detectors comparing stabilizers before/after noise.
    for k, m in enumerate(measure_qubit_set):
        circuit.append('DETECTOR', [stim.target_rec(-1 - k), stim.target_rec(-1 - k - len(measure_qubit_set))], [m.real, m.imag])

    # Measure observable afterward, assert it should match preparation.
    circuit.append('MPP', obs_targets)
    circuit.append('OBSERVABLE_INCLUDE', [stim.target_rec(-1), stim.target_rec(-circuit.num_measurements)], [0])

    return circuit


circuit = make_surface_code_capacity_circuit(d=45, p=5e-2)
matching = pymatching.Matching.from_stim_circuit(circuit)

n = 10_000
sampler = circuit.compile_detector_sampler()
dets, actual_obs = sampler.sample(shots=n, separate_observables=True)
predictions_solo = []
t0 = time.monotonic()
for shot_dets in dets:
    predictions_solo.append(matching.decode(shot_dets))
t1 = time.monotonic()
predictions = matching.decode_batch(dets)
t2 = time.monotonic()

np.testing.assert_array_equal(predictions_solo, predictions)
errors = np.count_nonzero(np.any(predictions != actual_obs, axis=1))
print("Error rate: ", errors / n)
print(f"Solo time per shot: {(t1 - t0) / n * 1000:0.3f} milliseconds")
print(f"Batch time per shot: {(t2 - t1) / n * 1000:0.3f} milliseconds")
```

which outputs:

```
Error rate:  0.0
Solo time per shot: 0.109 milliseconds
Batch time per shot: 0.088 milliseconds
```

please correct the timing data in the README to accurately represent the performance of pymatching.

Also, you should always accompany timing information by accuracy information, as speed-vs-accuracy is an important tradeoff when picking decoders.

**Comment by trevor-vincent** [comment]
Thank you both for the information. We plan on adding a decode_batch() function to plaquette-unionfind in the very near future. We expect a large speed-up as well from batching. After this addition we will update the benchmarks to compare our decode_batch function with the one from pymatching on a m6id.4xlarge AWS node. This should resolve any issues you have relating to caching.  Since we currently don't have a decode_batch() function, we intentionally only timed a single shot.

**Comment by Strilanc** [comment]
The issue is not that you didn't use batching. In the example code that I posted above, my not-using-batching timing result is 10x faster than the number you report in your plots. The issue is that you are timing *configuring the decoder* and not the *actual decoding time*.

If you are not going to fix the timing data within a few days, **please add a disclaimer to the plots noting that the timing data is known to be off by an order of magnitude and will be fixed**.

**Comment by trevor-vincent** [comment]
My apologies for missing your point @Strilanc, we're now looking into the issue deeper. Our understanding is that the initial benchmarks are correct for a single decode() function call, which as you rightly point out includes the configuration and decoding time.

We of course also agree they do not measure the true average single shot batch decoding speed, which is an important real-world metric. So in the meantime we have removed them altogether from the README. We appreciate your feedback and will reach out to you when we have updated benchmarks. 

I'm closing this issue for now, but feel free to re-open it if there is something else you'd like to discuss.

**Comment by Strilanc** [comment]
Okay, thank you. Looking forward to the cleaner benchmarks.
